### ISSUE TITLE
TLS: `testssl` parser not parsing list of supported cipher suites

### ISSUE THREAD

**Issue by 4elta** [4elta/recon#86]
see #85

in order for me to be able to look into and solve this issue i would kindly ask you (@ikstream or @Zeramo) to provide me the result files (i.e. `tls,*,testssl.json`).

thanks

**Comment by Akasch** [comment]
Here on (anonymized) File for "## Server scheint keine Cipher-Suites zu unterstützen" [tls_misc,tcp,25,testssl.json](https://github.com/user-attachments/files/15514604/tls_misc.tcp.25.testssl.json)
I have multiple more, also for web with Port 443
